version: "2"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tools/cmd/stringer.go
      - third_party$
      - builtin$
      - examples$

  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -ST1003

    tagliatelle:
      case:
        rules:
          json: camel
          path: camel
          query: camel
          db: snake
          env: upperSnake

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

