all: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
inpackage: false
issue-845-fix: true
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
resolve-type-alias: false
with-expecter: true

packages:
  autopilot/backends/internal/core:
    config:
      recursive: true

  autopilot/backends/api/pkg/app:
    config:
      recursive: true

  autopilot/backends/api/internal:
    config:
      recursive: true
