[tools]
go = "1.24.2"
node = "23.11.0"
"aqua:pnpm/pnpm" = "10.7.1"
"aqua:air-verse/air" = "1.61.7"
"aqua:aquasecurity/tfsec" = "1.28.13"
"aqua:aws" = "2.25.8"
"aqua:evilmartians/lefthook" = "1.11.6"
"aqua:golangci/golangci-lint" = "2.0.2"
"aqua:gotestyourself/gotestsum" = "1.12.1"
"aqua:hashicorp/terraform" = "1.11.3"
"aqua:stripe/stripe-cli" = "1.25.1"
"aqua:terraform-linters/tflint" = "0.56.0"
"aqua:vektra/mockery" = "2.53.3"
"aqua:aws/aws-cli" = "2.25.8"
"ubi:go-task/task" = "3.42.1"
